# Generated by Django 5.0.7 on 2024-07-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productvariant_id_alter_subvariant_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'product variant', 'verbose_name_plural': 'product variants'},
        ),
        migrations.AlterModelOptions(
            name='subvariant',
            options={'verbose_name': 'subvariant', 'verbose_name_plural': 'subvariants'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'variant', 'verbose_name_plural': 'variants'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.productvariant')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
    ]
