# Generated by Django 5.0.7 on 2024-07-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subvariant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={},
        ),
    ]
